[package]
name = "tymodem"
version = "0.2.0"
authors = ["Tommy van der Vorst <tommy@pixelspark.nl>"]
edition = "2018"

[dependencies]
serialport = "3.*"
clap = "2.*"
regex = "1"

[[bin]]
name = "tymodem-cli"
path = "src/tymodem-cli.rs"

